setwd("c:/Rdata")
setwd("D:/Data")
getwd()
rm(list=ls())

library(rvest)
library(stringr)
Sys.getlocale( )
Sys.setlocale("LC_ALL","C")
Sys.setlocale("LC_ALL","Korean")
library(KoNLP)
library(wordcloud)
library(wordcloud2)
library(dplyr)	
library(readxl)	
library(nortest)
library(plotly)
library(ggplot2)
library(foreign)
library(vctrs)
library(xts)
install.packages("ggmap")
library(leaps)
library(ggmap)
library(treemap)
library(Rtsne)
install.packages(c("rgl", "car"))
library("car")
library("rgl")
library("mgcv")
library(stats)
library(MASS)
library(car)
library(leaps)
